name: Dev Branch Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [dev]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd boilerplate-python/python/dev
            git pull origin dev
            source .venv/bin/activate
            pip install -r requirements.txt
            alembic upgrade head

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
