name: Prod cd pipeline
on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t anchor-python-bp-prod:latest -f docker/prod/Dockerfile .

      - name: Save image 
        run: docker save anchor-python-bp-prod:latest | gzip > prod.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "prod.tar.gz"
          target: "/home/${{ secrets.USERNAME }}/python-test/prod_source_code/docker/prod"
 
      - name: Deploy image on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/python-test/prod_source_code/docker/prod
            git pull origin main
            docker load --input prod.tar.gz
            docker compose -f docker-compose.yml up -d
            rm -f prod.tar.gz