name: Run Newman Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" 

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          sudo apt install jq

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults && mkdir -p downloaded-reports

      - name: Run Newman Tests here
        run: |
          newman run qatests/regression/HNG-Stage-7-Team-Anchor.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme --suppress-exit-code

      - name: Archive HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: testResults/

      - name: Get Artifact Download URL
        id: get_artifact_url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ARTIFACT_ID=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" /repos/${{ github.repository }}/actions/artifacts | \
            jq -r ".artifacts[] |
            select(.name==\"newman-report\") |
            select(.expired==false) |
            .id")

          ARTIFACT_URL=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" /repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip | \
            jq ".archive_download_url")

          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

      - name: Comment on PR with Report URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="Your Newman test report is available [here](${{ env.ARTIFACT_URL }})."
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"$COMMENT\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments