name: Run Regression Newman Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [dev, staging, main]


jobs:
  run-newman:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" 

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          sudo apt install jq

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run Newman Tests here
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
        run: |
          newman run qatests/regression/HNG-Stage-7-Team-Anchor.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport-pr-${{ github.event.pull_request.number }}.html --reporter-htmlextra-darkTheme --suppress-exit-code

      - name: Run Newman Tests on push here
        if: github.event_name == 'pull_request' && (github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: |
          newman run qatests/regression/HNG-Stage-7-Team-Anchor.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport-pr-${{ github.event.pull_request.number }}-merged.html --reporter-htmlextra-darkTheme --suppress-exit-code
      
      - name: Archive HTML report
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: testResults/

      - name: Post Report Link in PR
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            The newman reports are available to view here ${{ steps.artifact-upload-step.outputs.artifact-url }}

      - name: Post Report Link in PR
        if: github.event_name == 'pull_request' && (github.event.action == 'closed' && github.event.pull_request.merged == true)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            The newman reports are available to view here ${{ steps.artifact-upload-step.outputs.artifact-url }}

     
