name: Test cd pipeline
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t anchor-python-bp-dev:latest -f Dockerfile.dev .

      - name: Save image 
        run: docker save anchor-python-bp-dev:latest | gzip > dev.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dev.tar.gz"
          target: "/home/${{ secrets.USERNAME }}/python-test"
 
      - name: Deploy image on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/python-test
            docker load --input dev.tar.gz
            docker compose -f docker-compose.yml up -d
            rm -f dev.tar.gz

