name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          PYTHONPATH=. pytest
